#!/usr/bin/env bash

BASEDIR=$(dirname $0)
cd $BASEDIR

ln -bs ${PWD}/bashrc ~/.bashrc
ln -bs ${PWD}/tmux.conf ~/.tmux.conf
ln -bs ${PWD}/vimrc ~/.vimrc
ln -bs ${PWD}/gitconfig ~/.gitconfig
ln -bs ${PWD}/nvim ~/.config/
